#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
SERVICE_NAME="n8n"

cat <<EOF

****************************************************************************************
*                                                                                      *
*                    END OF LIFE NOTICE AUGUST 18, 2025                                *
*                               tiredofit/n8n                                          *
*                                                                                      *
* This image is no longer maintained as of and will not receive updates.               *
*                                                                                      *
* A successor image is available at:                                                   *
*                                                                                      *
* Repository | Documentation:                                                          *
*   - https://github.com/nfrastack/container-n8n                                       *
*                                                                                      *
* Image Registries:                                                                    *
*   - https://hub.docker.com/r/nfrastack/n8n                                           *
*   - https://github.com/nfrastack/container-n8n/pkgs/container/container-n8n          *
*                                                                                      *
* Please visit https://nfrastack.com for more information.                             *
*                                                                                      *
****************************************************************************************

EOF

sleep 15

if var_false ENABLE_NGINX ; then
	print_warn "Disabling Nginx - Using N8N in place server - Be sure to set Authentication!"
	service_stop 10-nginx
fi

liftoff
